pages:
  home:
     home: 0.45
     product_a: 0.22
     product_b: 0.18
     session_end: 0.15

  product_a:
     product_a: 0.6
     home: 0.18
     cart: 0.12
     session_end: 0.1

  product_b:
     product_b: 0.4
     home: 0.22
     cart: 0.14
     session_end: 0.24

  cart:
     cart: 0.3
     payment: 0.55
     home: 0.1
     session_end: 0.05

  payment:
     payment: 0.4
     confirmation: 0.45
     cart: 0.1
     session_end: 0.05

  confirmation:
     confirmation: 0.6
     session_end: 0.4

landing_pages:
  home: 0.6
  product_a: 0.25
  product_b: 0.15

events:
  home:
    click_product_a:
      prereq:
      prob: 0.5
      properties:

    click_product_b:
      prereq:
      prob: 0.3
      properties:

    dropdown_click:
      prereq:
      prob: 0.2
      properties:
        test_prop:
          type: 'email'

    dropdown_select:
      prereq: 'dropdown_click'
      prob: 1
      properties:
        drp_option:
          type: 'string'
          values: ['text1', 'text2', 'text3', 'text4']
        drp_order:
          type: 'int'
          values: [1, 4]

  product_a:
    click_home:
      prereq:
      prob: 0.05
      properties:

    click_product_b:
      prereq:
      prob: 0.05
      properties:

    click_zoom:
      prereq:
      prob: 0.6
      properites:

    add_to_cart:
      prereq:
      prob: 0.3
      properties:
        qty:
          type: 'int'
          values: [ 1, 10]
        price:
          type: 'float'
          values: [ 10, 30 ]

    remove_from_cart:
      prereq: 'add_to_cart'
      prob: 0.3
      properties:
        time_passed_sec:
          type: 'float'
          values: [0, 10]

    go_to_cart:
      prereq: 'add_to_cart'
      prob: 0.7
      properties:

  product_b:
    click_home:
      prereq:
      prob: 0.05
      properties:

    click_product_b:
      prereq:
      prob: 0.05
      properties:

    click_zoom:
      prereq:
      prob: 0.5
      properties:

    add_to_cart:
      prereq:
      prob: 0.4
      properties:
        qty:
          type: 'int'
          values: [ 1, 10 ]
        price:
          type: 'float'
          values: [ 10, 30 ]

    remove_from_cart:
      prereq: 'add_to_cart'
      prob: 0.3
      properties:
        time_passed_sec:
          type: 'float'
          values: [ 0, 10 ]

    go_to_cart:
      prereq: 'add_to_cart'
      prob: 0.7
      properties:
  cart:
    go_to_home:
      prereq:
      prob: 0.1
      properties:

    go_to_pay:
      prereq:
      prob: 0.6
      properties:
        time_passed_sec:
          type: 'float'
          values: [ 0, 10 ]

    clear_cart:
      prereq:
      prob: 0.2
      properties:
        num_items_cart:
          type: 'int'
          values: [1, 5]

    confirm_clear:
      prereq: 'clear_cart'
      prob: 0.8
      properties:

    cancel_clear:
      prereq: 'clear_cart'
      prob: 0.2
      properties:

  payment:
    go_to_home:
      prereq:
      prob: 0.05
      properties:

    add_cc:
      prereq:
      prob: 0.8
      properties:
        franchise:
          type: 'str'
          values: ['mastercard','visa','american_express']

    select_cc:
      prereq:
      prob: 0.15
      properties:
        franchise:
          type: 'str'
          values: [ 'mastercard','visa','american_express' ]

    confirm_payment:
      prereq: 'select_cc'
      prob: 0.9
      properites:

    cancel_payment:
      prereq: 'select_cc'
      prob: 0.1
      properties:

  confirmation:
    go_to_gome:
      prereq:
      prob: 0.15
      properties:

    print_confirmation:
      prereq:
      prob: 0.6
      properties:

    exit_session:
      prereq:
      prob: 0.25
      properties:

visits_per_hour:
  0: 0.0273
  1: 0.0185
  2: 0.0108
  3: 0.0107
  4: 0.0050
  5: 0.0105
  6: 0.0192
  7: 0.0297
  8: 0.0382
  9: 0.0426
  10: 0.0549
  11: 0.0583
  12: 0.0646
  13: 0.0627
  14: 0.0572
  15: 0.0521
  16: 0.0590
  17: 0.0667
  18: 0.0718
  19: 0.0662
  20: 0.0696
  21: 0.0428
  22: 0.0329
  23: 0.0287

operating_systems:
  Windows: 0.1
  MacOS: 0.15
  Linux: 0.05
  Android: 0.3
  iOS: 0.4

utm_sources:
  google: 0.15
  facebook: 0.3
  bing: 0.05
  instagram: 0.2
  mailchimp: 0.3

ads:
  ad_1: 0.05
  ad_2: 0.3
  ad_3: 0.2
  ad_4: 0.25
  ad_5: 0.2

campaigns:
  campaign_1: 0.8
  campaign_2: 0.2

utm_mediums:
  cpc: 0.25
  affiliate: 0.1
  organic: 0.4
  social: 0.25

browsers:
  Chrome: 0.5
  Firefox: 0.25
  InternetExplorer: 0.05
  Safari: 0.1
  Opera: 0.1
